### ISSUE TITLE
Error encountered: dictionary changed size during iteration

### ISSUE THREAD

**Issue by gaspardc-met** [vega/altair#3554]
### What happened?

When trying to create an altair chart within a streamlit application, I run into `Uncaught Exception: dictionary changed size during iteration`. Running altair 5.4.0 here, and downgrading to 5.3.0 seemed to solve this specific issue at the moment.

This is with streamlit caching removed:
Error stack: 
```python 
Traceback (most recent call last):
  File "/path/to/project/decorators.py", line 68, in wrapper
    result = main_func(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/file.py", line 81, in main
    display_tab(
  File "/path/to/project/file.py", line 224, in display_tab
    display_chronograms(
  File "/path/to/project/predictions/plots.py", line 513, in display_chronograms
    plot_chronogram(
  File "/path/to/project/predictions/plots.py", line 328, in plot_chronogram
    .encode(
        ^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/altair/vegalite/v5/schema/channels.py", line 31233, in encode
    kwargs = _infer_encoding_types(args, kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/altair/utils/core.py", line 964, in infer_encoding_types
    return cache.infer_encoding_types(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.11/site-packages/altair/utils/core.py", line 870, in infer_encoding_types
    return {
  File "/path/to/venv/lib/python3.11/site-packages/altair/utils/core.py", line 870, in <dictcomp>
    return {
RuntimeError: dictionary changed size during iteration
```

I have had this error intermittently in the past, only on cloud deployments, and with altair 5.2.0. 
Since at the time it was intermittent and in production I attributed it at the time to a streamlit cache issue (https://github.com/streamlit/streamlit/issues/8409)
Now this error is happening locally, even when I remove any caching mechanism, and it's not intermittent, it never works for that specific plot. Downgrading to altair 5.3.0 seemed to fix the issue on this specific plot for now. 

I'm working on a minimal reproduction code example, but at the moment it fails to produce this error on my side with dummy data. 

### Which version of Altair are you using?

5.4.0

**Comment by gaspardc-met** [comment]
Still cannot manage to reproduce the error with dummy data, but these are basically the plot operations:

numpy==2.1.0
Pandas==2.2.2
streamlit==1.37.0

```python
import pandas as pd
import altair as alt
import streamlit as st
import functools
import numpy as np
import random

# Dummy data for the chronogram
data = pd.DataFrame(
    {
        "start_time": pd.date_range("2023-01-01", periods=100, freq="H").tz_localize("Europe/Paris"),
        "end_time": pd.date_range("2023-01-01 01:00", periods=100, freq="H").tz_localize("Europe/Paris"),
        "asset": ["Asset " + str(i % 5) for i in range(100)],
        "load": [float(np.random.uniform(40, 100)) for _ in range(100)],
    }
)

# Set most 'load' values for 'Asset 0' to NaN or None
asset_0_indices = data[data["asset"] == "Asset 0"].index
indices_to_nullify = random.sample(list(asset_0_indices), k=len(asset_0_indices) - 2)  # Keep only 2 non-NaN

data.loc[indices_to_nullify, "load"] = np.nan  # Set
data = data.reset_index()

# Placeholder functions for processing and legend (you would replace these with actual logic)
def chronogram_legend(target, pump_toggle):
    return "Legend", "Short Legend", "Other Info"


def chronogram_processing(chronogram, timedelta, filter_load):
    return chronogram  # Simply returns the input data in this dummy example


def custom_blues():
    return ["low", "medium", "high"], ["#dceefb", "#86c7f3", "#1f77b4"]


def get_assets_starts_and_stops(chronogram, timedelta, separator_dt):
    # Simple dummy start/stop markers within the range
    starts_and_stops = alt.Chart(chronogram).mark_rule(color="red").encode(x="start_time:T")
    starts_and_stops_texts = (
        alt.Chart(chronogram)
        .mark_text(align="left", dx=5, dy=-5, color="red")
        .encode(x="start_time:T", text=alt.value("Start/Stop"))
    )
    return starts_and_stops, starts_and_stops_texts


def get_vertical_separator(separator_dt, labels_y, y_field):
    return None, None  # Placeholder for the actual function output


# Main function with dummy data and simplified inputs
def plot_chronogram(
    data: pd.DataFrame,
    formatted=".0f",
    target="load",
    timedelta="60min",
    filter_load=True,
    expand: bool = False,
    pump_toggle: bool = False,
    display_starts_and_stops: bool = False,
    separator_dt: pd.Timestamp = None,
):
    # Get legend information
    legend, short_legend, _ = chronogram_legend(target=target, pump_toggle=pump_toggle)

    # Process the data (dummy in this case)
    st.write(data.dtypes)

    # Example of expanding the time (dummy logic here)
    if expand:
        data = data.set_index("start_time").sort_index().reset_index()
        data.loc[28:, "end_time"] = data.loc[28:, "end_time"] + pd.Timedelta("45T")

    # Set up the color scale (dummy logic here)
    if target == "pressure":
        bins, colors = custom_blues()
        scale = alt.Scale(domain=bins, range=colors, type="ordinal")
    elif target == "load":
        scale = alt.Scale(domain=[0, 50, 100], range=["#f7fbff", "#6baed6", "#08306b"], type="threshold")
    else:
        scale = alt.Scale(scheme="blues")

    # Define the sorting order for the y-axis
    sort_order = [""] + data["asset"].sort_values().unique().tolist()

    # Main bar chart
    chart = (
        alt.Chart(data)
        .mark_bar()
        .encode(
            x=alt.X("start_time:T", title="Horizon Temporel"),
            x2=alt.X2("end_time:T", title=""),
            y=alt.Y("asset:N", title="Utilisation: Groupes ou AFC", sort=sort_order),
            color=alt.Color(
                "load:Q",
                title=short_legend,
                scale=scale,
                legend=alt.Legend(title=legend),
            ),
            stroke=alt.value("white"),
            strokeWidth=alt.value(2),
            tooltip=[
                alt.Tooltip("start_time:T", format="%Y-%m-%d", title="Date"),
                alt.Tooltip("start_time:T", format="%H:%M", title="Heure"),
                alt.Tooltip("load:Q", format=formatted, title=legend),
            ],
        )
    ).properties(
        title=f"Chronogramme d'opération: {legend}",
        width=1100,
        height=350,
    )

    # Text overlay layer
    text = (
        alt.Chart(data)
        .mark_text(dx=0, dy=0, color="white", fontSize=25)
        .encode(
            x=alt.X("mid_time:T", title=""),
            y=alt.Y("asset:N", title="Utilisation: Groupes ou AFC", sort=None),
            text=alt.Text("load:Q", format=formatted),
            tooltip=[
                alt.Tooltip("start_time:T", format="%Y-%m-%d", title="Date"),
                alt.Tooltip("start_time:T", format="%H:%M", title="Heure"),
                alt.Tooltip("load:Q", format=formatted, title=legend),
            ],
        )
    ).transform_calculate(mid_time="datum.start_time + (datum.end_time - datum.start_time)/2")

    # Additional text layer for a specific condition
    text_hot = (
        alt.Chart(data)
        .mark_text(dx=0, dy=0, color="white", fontSize=25)
        .encode(
            x=alt.X("mid_time:T", title=""),
            y=alt.Y("asset:N", title="Utilisation: Groupes ou AFC", sort=None),
            text=alt.value("Chaud"),
            tooltip=alt.value(None),
        )
    ).transform_calculate(mid_time="datum.start_time + (datum.end_time - datum.start_time)/2")

    # Store all charts to be layered
    all_charts = [chart, text, text_hot]

    # Example of including start and stop markers (dummy logic here)
    if display_starts_and_stops:
        starts_and_stops, starts_and_stops_texts = get_assets_starts_and_stops(
            chronogram=data,
            timedelta=timedelta,
            separator_dt=separator_dt,
        )
        all_charts += [starts_and_stops, starts_and_stops_texts]

    # Example of adding a vertical separator (dummy logic here)
    display_separator = separator_dt is not None and separator_dt > data.index.min()
    if display_separator:
        separator, separator_labels = get_vertical_separator(separator_dt=separator_dt, labels_y="", y_field="asset")
        all_charts += [separator, separator_labels]

    # Combine all chart layers
    composed = (
        functools.reduce(lambda a, b: a + b, all_charts)
        .configure_legend(orient="right", titleOrient="right")
        .configure_axis(labelFontSize=15, titleFontSize=15)
    )

    # Display the composed chart in Streamlit
    st.altair_chart(altair_chart=composed, use_container_width=True)


# Test the function with dummy data
plot_chronogram(data=data, display_starts_and_stops=True)
```

**Comment by dangotbanned** [comment]
Appreciate the detail here @gaspardc-met in https://github.com/vega/altair/issues/3554#issuecomment-2304319269, but a [minimal repro](https://matthewrocklin.com/minimal-bug-reports) would be helpful.
`Uncaught Exception: dictionary changed size during iteration` is being raised within a `(LayerChart|Chart).encode()`. 
No idea which one though, as there seem to be a few.

I copied your code directly, commenting out the `streamlit` parts and didn't get any errors.
I added some additional checks at the end, all seem to be working as expected.

<details>
<summary>Repro without streamlit</summary>

```py
def test_infer_encoding_types_mod_iter() -> None:
    import pandas as pd  # noqa: I001
    import altair as alt

    # import streamlit as st
    import functools
    import numpy as np
    import random

    # Dummy data for the chronogram
    data = pd.DataFrame(
        {
            "start_time": pd.date_range(
                "2023-01-01", periods=100, freq="H"
            ).tz_localize("Europe/Paris"),
            "end_time": pd.date_range(
                "2023-01-01 01:00", periods=100, freq="H"
            ).tz_localize("Europe/Paris"),
            "asset": ["Asset " + str(i % 5) for i in range(100)],
            "load": [float(np.random.uniform(40, 100)) for _ in range(100)],  # noqa: NPY002
        }
    )

    # Set most 'load' values for 'Asset 0' to NaN or None
    asset_0_indices = data[data["asset"] == "Asset 0"].index
    indices_to_nullify = random.sample(
        list(asset_0_indices), k=len(asset_0_indices) - 2
    )  # Keep only 2 non-NaN

    data.loc[indices_to_nullify, "load"] = np.nan  # Set
    data = data.reset_index()

    # Placeholder functions for processing and legend (you would replace these with actual logic)
    def chronogram_legend(target, pump_toggle):
        return "Legend", "Short Legend", "Other Info"

    def chronogram_processing(chronogram, timedelta, filter_load):
        return chronogram  # Simply returns the input data in this dummy example

    def custom_blues():
        return ["low", "medium", "high"], ["#dceefb", "#86c7f3", "#1f77b4"]

    def get_assets_starts_and_stops(chronogram, timedelta, separator_dt):
        # Simple dummy start/stop markers within the range
        starts_and_stops = (
            alt.Chart(chronogram).mark_rule(color="red").encode(x="start_time:T")
        )
        starts_and_stops_texts = (
            alt.Chart(chronogram)
            .mark_text(align="left", dx=5, dy=-5, color="red")
            .encode(x="start_time:T", text=alt.value("Start/Stop"))
        )
        return starts_and_stops, starts_and_stops_texts

    def get_vertical_separator(separator_dt, labels_y, y_field):
        return None, None  # Placeholder for the actual function output

    # Main function with dummy data and simplified inputs
    def plot_chronogram(
        data: pd.DataFrame,
        formatted=".0f",
        target="load",
        timedelta="60min",
        filter_load=True,
        expand: bool = False,
        pump_toggle: bool = False,
        display_starts_and_stops: bool = False,
        separator_dt: pd.Timestamp = None,
    ):
        # Get legend information
        legend, short_legend, _ = chronogram_legend(
            target=target, pump_toggle=pump_toggle
        )

        # Process the data (dummy in this case)
        # st.write(data.dtypes)

        # Example of expanding the time (dummy logic here)
        if expand:
            data = data.set_index("start_time").sort_index().reset_index()
            data.loc[28:, "end_time"] = data.loc[28:, "end_time"] + pd.Timedelta("45T")

        # Set up the color scale (dummy logic here)
        if target == "pressure":
            bins, colors = custom_blues()
            scale = alt.Scale(domain=bins, range=colors, type="ordinal")
        elif target == "load":
            scale = alt.Scale(
                domain=[0, 50, 100],
                range=["#f7fbff", "#6baed6", "#08306b"],
                type="threshold",
            )
        else:
            scale = alt.Scale(scheme="blues")

        # Define the sorting order for the y-axis
        sort_order = [""] + data["asset"].sort_values().unique().tolist()  # noqa: RUF005

        # Main bar chart
        chart = (
            alt.Chart(data)
            .mark_bar()
            .encode(
                x=alt.X("start_time:T", title="Horizon Temporel"),
                x2=alt.X2("end_time:T", title=""),
                y=alt.Y(
                    "asset:N", title="Utilisation: Groupes ou AFC", sort=sort_order
                ),
                color=alt.Color(
                    "load:Q",
                    title=short_legend,
                    scale=scale,
                    legend=alt.Legend(title=legend),
                ),
                stroke=alt.value("white"),
                strokeWidth=alt.value(2),
                tooltip=[
                    alt.Tooltip("start_time:T", format="%Y-%m-%d", title="Date"),
                    alt.Tooltip("start_time:T", format="%H:%M", title="Heure"),
                    alt.Tooltip("load:Q", format=formatted, title=legend),
                ],
            )
        ).properties(
            title=f"Chronogramme d'opération: {legend}",
            width=1100,
            height=350,
        )

        # Text overlay layer
        text = (
            alt.Chart(data)
            .mark_text(dx=0, dy=0, color="white", fontSize=25)
            .encode(
                x=alt.X("mid_time:T", title=""),
                y=alt.Y("asset:N", title="Utilisation: Groupes ou AFC", sort=None),
                text=alt.Text("load:Q", format=formatted),
                tooltip=[
                    alt.Tooltip("start_time:T", format="%Y-%m-%d", title="Date"),
                    alt.Tooltip("start_time:T", format="%H:%M", title="Heure"),
                    alt.Tooltip("load:Q", format=formatted, title=legend),
                ],
            )
        ).transform_calculate(
            mid_time="datum.start_time + (datum.end_time - datum.start_time)/2"
        )

        # Additional text layer for a specific condition
        text_hot = (
            alt.Chart(data)
            .mark_text(dx=0, dy=0, color="white", fontSize=25)
            .encode(
                x=alt.X("mid_time:T", title=""),
                y=alt.Y("asset:N", title="Utilisation: Groupes ou AFC", sort=None),
                text=alt.value("Chaud"),
                tooltip=alt.value(None),
            )
        ).transform_calculate(
            mid_time="datum.start_time + (datum.end_time - datum.start_time)/2"
        )

        # Store all charts to be layered
        all_charts = [chart, text, text_hot]

        # Example of including start and stop markers (dummy logic here)
        if display_starts_and_stops:
            starts_and_stops, starts_and_stops_texts = get_assets_starts_and_stops(
                chronogram=data,
                timedelta=timedelta,
                separator_dt=separator_dt,
            )
            all_charts += [starts_and_stops, starts_and_stops_texts]

        # Example of adding a vertical separator (dummy logic here)
        display_separator = separator_dt is not None and separator_dt > data.index.min()
        if display_separator:
            separator, separator_labels = get_vertical_separator(
                separator_dt=separator_dt, labels_y="", y_field="asset"
            )
            all_charts += [separator, separator_labels]

        # Combine all chart layers
        composed = (
            functools.reduce(lambda a, b: a + b, all_charts)  # noqa: FURB118
            .configure_legend(orient="right", titleOrient="right")
            .configure_axis(labelFontSize=15, titleFontSize=15)
        )

        # Display the composed chart in Streamlit
        # st.altair_chart(altair_chart=composed, use_container_width=True)
        return composed

    # Test the function with dummy data
    composed = plot_chronogram(data=data, display_starts_and_stops=True)

    # NOTE: Reaching here wouldn't be possible if the error raised
    validated = composed.to_dict(validate=True)
    # NOTE: Another error would have been raised if the spec we returned was not valid
    assert isinstance(validated, dict)

    # NOTE: These may require optional dependencies you don't have,
    # but provide more evidence of the spec produced being valid
    vega_editor_url = composed.to_url()
    assert isinstance(vega_editor_url, str)
    composed.open_editor()

```

</details>

If you do not have the required dependencies for `Chart.open_editor`, see in [Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvtwCGADziU8IADYyARphUAxXgGU4AL0woAjAFZuxQisy6iB42fPTVmBJih1lEAE5YiFBB-BDEQKzgbTAB5f09xZGDRcUlXNQBPTF8UAG1QAFsZXwBrZUJ0gAcTRPUikFdPSDoSJFQeFT9leC1vRI6Zb25bDy8yyNsggBl3T29XSjAZCba6CEKSXK5zLlMOAF1uXxkoD1yQAGIYAHYYdRgYcIuANlrMOifH87YADnYXkAOIHKVSCTF8mEojAgKjmESiQT0UN8hAABNMRoMgZVqiAAI6kY7WGTENAmeaEXwQYrVdBLUg47CMSJk7iUClUzC0BjMNpoOnVABMrkIEGhxAquVA3RhQTZRUIAH1iPkTNwYH5CgkQABSACaAFptflDZjrMsQAARYmqrEgxKETD5Cp+Jb1ThSrAyxJy5FKuAqx7q3yaoLawTIbUAWUeZpxwlI4Jj2NBjudRxUbo9PSC-UxQZDiQAdGwHnDzejZkm7XiCURIsS4KT6oC5F1Pb0QD7FcqbbGgoI-EZoCiACqpvxaKs4h1Ol0Z1xyAVt7OJWZ+gNlnFukDpZdekAySiUTDiVl+BI5ECPACCR5PKLYN7vqNMT+PqKX3Fv75RLDf94AFgBTcggAVWIFRFAbaBkBRABxSlSCqSgUQoFFr20ABhKcgigNYSFdVIQMSTDGEpPCECOfIVRROgAHIIAqABLo5iBgtEZlGaQCiKUo2mBadMDkU92k6RJGWZR46FbZAuBAOhd1ktV9CMQUXG4RoIGaE4yiEhIs33XNAw1YkgmLUtbRxfFCXrEkWSBUUVHFSUQGlDsu3XG181MxI9UNY1tVNcYcStB0cPtcd00zVz21lQh5U84zgx8nVwyjGNgv7TAE17ZMItnKLuJildVAgAYkoLEBzIy+FEgrUYrDymsbPiuzm24GSDI7fJ6ES4ir0a6sZzTQjuEUrqgkPd9Hkoc8UDIFQVH68C4EgyhoKgWCEIoZDUNIdCsPCkA8J6qBCOFI4oEofMXMWFQwFINQwsSOhiVIfJCw8nsUQAahRAAKV7CHews12+-VaLej6vv9TAAEoAHpPwPJREh6uhEskPYisKEoyiah1hMeSAOmycSmTC7hpJQOSFJp5SHFUlABXUkBNO01pQEJ-SQD5FR6SCUiZFIWEHLFOAJV5fl5selQFz3brep7GrzSO4a523cbiv3KaTxmubkAWpagUyxIVrWjatsQ3a0Iw7DBpxE6CPnC7jmujVbqWB6npxIGQZhmi-sBqHQa8TyUQhv3ofi30e0R5HDyCdHMex90QFxviuaa3xHptEmxOCN5t3ZlplE67X3Jj7tYbVyLzpx3j8aGvTHiWRAoBzTAYBE-OycLzFqeQSx5MU-VWZLnT+JbqX+ZxPQq4R+fGO3cu3LihLlYdlMCvrwEgZkZQzoDF7iRkMffm+dQrk0ACrjATBzAAThkR+YBkS+ngFOh1FMdRzFv9Qn9tyMBEKEBILBtjcGwPQJgZhdhyQACQLBAYUIIYhCAVEoMgBGCNSQIBkIWBAkRGCkHUIWOAEAEbIMdDIXB7gz6QQdLg8whYBRsELKYQsAArWaHcqan3fKjUA+9z4sEvtfTAt975Pxfm-D+X8f5-wAUA5AeQQAkDoEJemnYq6JUSGwgULB9RsFMMY0wI4OCyTYFYn6JirGPDBjXfRbBDFmLMRY0wVibF2I4K3Z8QRvz3kfEMMqvQjZFQ0Vo5AphWS6OVs41xJj3E+OsRwWxnjfEaTDvEkABijFJJMRYgUXi0kpL8dNRIgSXyPCMsgK4AoOH1JZlcK43w2AtLEY-CJXgokCliRvJxuSXH5NMYUlxJS2DpPsVkjGOS8luLGSwCZUzMkowqSAKpKJka1O+E8QsTwAKPx+I-R+pg2GmBYI-dSoBIkyRYP02Ogz5kFPMWwJZljSkZOCWzbJTzhkLNeQBZZZTZD+Mqc+X8NTQkoG+FcQslyBTfG+OYNpAF-4sAFKYbpmiZIAQedXY+QzEmjMBcCr5DjfmEueSSix5gyXTLWXrcFP4gIhPKkPR+HCTHIt2U8UwVwWAsAAiwbFUTh4BxxNS5JdKPmTJBT82ZfziXJKePS1ZustSbO+bU8JadbkoCePivRRKRkqrVd8xxVL-kvIsVcc15SmUbIha+NlvQALfHhSwJ4VxzD1IgVcA5iLRUySuEauZ1qaXtPtTM41UqxnfGjYyzVELtnQuQABdhbAnguIsABACTxzDmAucGmFYalWmvjYmy1kqI3JMfomjVASIV-ldSgAVhZH5XDYOYS5phb6fz5SW5Aj8y1WuVWM+tsqVkWspTW8d5jdgNrBU6llUL2X-3hWwntTwxG-Efkiq4Q7dijrnRWhdqSL3TopYqsdZ6RymC+d48loL1larXWE2WR6Yk6IGbegF97H2fIZdWoIcaF3FKnfKxtzL7wutKuuj1PwM3mGzUci5-KnhHr6T+x5f6bVnKrbO0DtbCkXKXa+lN76UC30LOYTFGbb4CkxZiq4eaj33JwwS09-6yOQefQq2NJGF1Ar4wy6DK77wtvg70QtHDP6XKeI-ACAongFsU0evFnHBPzvvSJy98qQMJLvRYcjjrNmsukygR+LAOGCr7cp2F7rBWYb1T0mSFgT3EZ0yZ0TqzDMmp46q3z3zxNvtbYbT9rmcVmENVp8N3mgv6f4-5sD967XBYdcmn8cHak+vhaYTtTGfUqYFEc74R7Q1xfLTx9LSXgNEaMzxhNGWX1mco+Fx+eyMWtNaRwItQqWZHu+J5xr+Hmt1b8w1gL+HJ0TZC8uzZUmdk2ZYFcB93wBStIFPm0wO6j0jqq3hmlBXCM3u4zathpmsuASo0PBphyCt8tY96k5Yih1sJG9Nmll2WsCfi3ezFV2m0-m1Wm3VNy3PM2-RKrzAPANyuS1N1LTGgcweqeF1jhY1treOZc1pSnytRd6dhmHo3vsQbm9e7TAP3mU9a9dj8t3vgAX2Wio5WbfXbAK9c9RkPkCGM+8j2nT76tndhwsgUFiL0i-VQt5tt2Wn5bYIc5ngrfUYve5p0nX3jGS9lTLmdYuye648ajiTqILO1Jo4pwta2AK7Do5toUROZIs0FyRvX8Or0xv+xLopZuwuWeQN8Tl3XdkcE28z4tLvmaxe13GvXFODdU99wUvXwugOy4o9l27eaOEopUyrjnVwukx-55V+PHuLEZ4R6L6nfvlcB-a0HxXuz6M9sufmnth6y+Ivd+OvXenk8++q2n2lTefxLbTb6wsaLdh8us7fQVeaef6v5wdyvA-x+-ZS1XrNE+bsdZZ6t9gFgd2dr7d2od7B+8Vr14l4ff3R+jL17Vx-oWIWg-ZeD3n0XkAsGhziWfxNyjR3yRz33G3fzlxz3Cxozo2ZzzVaU-mVyYxcwhz-wxVvwb0gMz0N3rzHzYFmygOz3vFTXZT5Sx3qWVwAIsH-guR73QKiUFSwIIKINwJT2AJcXvWl3YPp2B0k1zw9Wc1aTRR9Xt1Xz5yFRYJf24NO3wJkIfQPwt1uwoLEXzTtyUxOSUyxTLwgWkJN0ULAKNx1y4II1+w-xB1ux-zXy9X0NMKT14KfyOwMJr29yTX4PRyDw3U6wK0MROWRQzUG10IryAOcNMNcIM3AK3z7SUK2Vz2P29QFUxQLxL3tzQN-yYOG0O3OwUKH0cN32iJlTp3cLR0hQxxZ2sx9XYF+HqRLyRWvw31CJyIMKKMfwKLv3vQf0cIsMPyD2Zyxy53oPaSLUIJFTLwzTsMl12zkNTwULf26OgKCSsMi0YNxUAN-WaNMPmNr0m2MIT3vRwJ2PmxIM8NqW9WLFOQww4ESIFQYIyNxRJyaPFzH1MEOLcPaL9xO3MMWMZwxz2R+EMS9TaQDQxWsyHWFUmPvTYKOI4LCMlx+2KJ6NRCn3ZSOVo2BI6Q4F2HYDuLXzzUhIRLaKiI6MB2+JOJREtzTTW32RZg7xQ0IKc3BPFSeONy4NJOKI+LHxRzJLa0sPC1+FZ27XaQAN2XzTeXBLjxZJMPhIcJhJHzhJHEMViJyzTWRVZ2ZxLxaQFR7RQ3BJCI2OeJkKVKMPkOMRYCl1iLIN6C7UoMMTbxQyuQOXBKyM3wrXNP13yOJIWXdK9ygx+LKKD0OU9R3VK29V7S7R0NWOo0aINNZJ9JmM4PdNlLcKRIpIV05RaSKyQ3zVKzGKjKHjkldO9P9xNNmLNOr1iK-w-UWiHSLTsPdIiMRz2JI3dLyLlJKPNxRBVNRJsxQwFWzSeF+D7W2FxL5zo3rIsTbPeK9IKXdNaIWPJKtINRYU0JOUIKfh3UOXSLXx7QnO7QTLCPdK6PbNTJRN6CRSxwOXaVOW1OFQAlrK1ylLjSPIPM2PdO2JTP9MpPZRtOVx7RD1eKuTYU61rOZNjJMPfNfMNPLJ+ErOWJrLLxQz3LeMiObPHXdOhM-PJO7LdQaUfkMXdU63-nzRD3vMQv1NwzfIsUwtQtNLeVkJ5IZziI6xXPEO+HQyRUHPU0QpdKfJbIYo5JnNGXNMMMRP9LPLbRYUMR9ULULVORQzIvzKfgnNEqJLQrdPvWTL9PJO-N6HOMUwuVOUFSFPdUUvuINULL4vQs0qgrjPvUbLE39KrJlgQvzL5RUoct2LopEqnO0t5NgyZxYV6xUx3UHI4qHU-hUt8qbO8vvXnJPP9KXODw9TzV+E3MLTeWHIio4yLNnLitsogs6NiIkuQAOVn1GOUy7TzQLWdzcsfPAufKKtLMTLS1iN0qsxsxZi9QDW2B8M-kJzcrAsougvov5QKsateLgvC2sL51UxUpQpirLNGpov41TJwphRszQ29W7263qTMrX29RUpWrryWvNMJIXP8t+MDNDy3IHI22zWjzct4oav4vOvbM5OEsVN9NWvEtuyuU3W2EORRUzMHNHL-0UwnPZLUtiu5LEp0r+q61zR+HWyUx3QkL-y7Uhq0sWpauNLhsuofHgrljLzW0hs8rwKWoAgtMYo8K7L+vYR2yOWSNeMRXtyHXqTsKpo9PeqEuMS5u+scsXNuzo2LEUw4C9QG0U1hW3L5wFU5tN2arCK5uxsFoJpKs6xpLRRcSLXt12123ZvquGtZOVvGpIy5vJsy1pvauDz2Qd0MquRIuzX2tlqGq4xGvNtNvHS5uitVqYucoi1cvMrqUlJeq9snM9orS5viqwoJvWvTQaRDyRV+G7RKwzTzKDpaXlv3MVs2K5uPJjqYqSs-nhUINU2BMLT5R7XZueqNpMLzojoWS5o-L8qYpKvqXhU-h9U7Qeoj3TrXxLyzubpxqVosQWt9qtuFr2R6o22BoKwDTBqiTaSzrHq8spuoqmqDxmr-3YqzuOtXs4KpsXRptKLjtaQ7ROWaQxQgVCudu3seNDsjoEuhrXtUousLr+o9TowxTaW7RaT7IGqDt+Hltfp5vUsbpsuPs7JKrVP5VeIw2zVZplu3sNrduNogcErAYKUPotr4NKOtvbs22FQHKzUuW7VL3zORWAZwacNzt0w3p1RWMAZDtrrjUPp9v3pHp83xqYtPoSM6xIoMTK0jMAYotQbrvypzvdqau4dpqSpL3hXYusyzW7QsHwqHSRWAfztopfqHvHtKOgc4WIt2AzRku2CdLLxD2Ad0Y4docmsgfM2FrhW6qzT7U62V2Uz7r5yOWAZXopoPqhPobB0YbX1OWAb3r8ZHreoLtprjvzQuL1o7xDzUKQaiXwvlqie0f8ahrftkaZ04QZPdVhVWz7QLXRtSZyqssfuydAboqpthuILVtz3YWQNUyexRXzUuTKZkiU3SZVpsakbxoaaYuto1uK33WY0RTeU7SHSuXSeoY+uMXMGppkdKP9q3tSeYbEbjSWe5unMwdGR2YFqz1jqZzhTzQlqoJQ03JmdEbosOYboKR2b6eOIJrkfYTaVOTaV2VaSfleJmZrq2ZIyeYeYOYrPsfl3C1U0LGRSLVaWMs21GJmZjJYaBbBYwbufDvBdXVgIaURTaR7VTpK1YyxlSCAA)

<details><summary>Screenshot of Vega Editor</summary>
<p>

![image](https://github.com/user-attachments/assets/52e4782d-2690-4f6b-a1ac-9286476b9986)


</p>
</details>

**Comment by dangotbanned** [comment]
Closing as it appears to be a downstream issue in `streamlit`.

@gaspardc-met please feel free to comment if you feel I've made a mistake in this assessment
