### ISSUE TITLE
_TypedDictMeta error on altair import

### ISSUE THREAD

**Issue by jgunstone** [vega/altair#3649]
### What happened?

I get the following error with a fresh install of altair: 

**create env**
```console
mamba create -n alt-test python pandas altair
mamba activate alt-test
```

**version**
```console
(alt-test) jovyan@PORT8002:~/tmp/altair-test$ mamba list alt
List of packages in environment: "/home/jovyan/micromamba/envs/alt-test"

  Name    Version  Build         Channel
──────────────────────────────────────────────
  altair  5.4.1    pyhd8ed1ab_1  conda-forge
```

**error**
```console
(alt-test) jovyan@PORT8002:~/tmp/altair-test$ python
Python 3.13.0 | packaged by conda-forge | (main, Oct  8 2024, 20:04:32) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import altair as alt
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import altair as alt
  File "/home/jovyan/micromamba/envs/alt-test/lib/python3.13/site-packages/altair/__init__.py", line 650, in <module>
    from altair.vegalite import *
  File "/home/jovyan/micromamba/envs/alt-test/lib/python3.13/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v5 import *
  File "/home/jovyan/micromamba/envs/alt-test/lib/python3.13/site-packages/altair/vegalite/v5/__init__.py", line 4, in <module>
    from .api import *
  File "/home/jovyan/micromamba/envs/alt-test/lib/python3.13/site-packages/altair/vegalite/v5/api.py", line 618, in <module>
    class _ConditionClosed(TypedDict, closed=True, total=False):  # type: ignore[call-arg]
    ...<6 lines>...
        value: Any
TypeError: _TypedDictMeta.__new__() got an unexpected keyword argument 'closed'
```

### What would you like to happen instead?

it works! 

### Which version of Altair are you using?

5.4.1

**Comment by jgunstone** [comment]
it does - thank you

this issue is already being tracked here: 
https://github.com/vega/altair/issues/3620
