### ISSUE TITLE
AttributeError: attribute '__default__' of 'typing.TypeVar' objects is not writable

### ISSUE THREAD

**Issue by benjamin5988** [vega/altair#3692]
### What happened?

I am using AutoEIS, which uses impedance.py, which calls altair - the following error happens:

```

> Traceback (most recent call last):
>   File "/home/bketter/csteis_working/11012024_NA2SO40pt1_FESO40pt001_NpH4_no6/autoeis_runscript_11012024_NA2SO40pt1_FESO40pt001_NpH4_no6.py", line 7, in <module>
>     import autoeis as ae
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/autoeis/__init__.py", line 6, in <module>
>     from .utils import Settings as _Settings
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/autoeis/utils.py", line 46, in <module>
>     from impedance.models.circuits import CustomCircuit
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/impedance/models/circuits/__init__.py", line 2, in <module>
>     from .circuits import *  # noqa: F401, F403
>     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/impedance/models/circuits/circuits.py", line 3, in <module>
>     from impedance.visualization import plot_altair, plot_bode, plot_nyquist
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/impedance/visualization.py", line 1, in <module>
>     import altair as alt
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/altair/__init__.py", line 650, in <module>
>     from altair.vegalite import *
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/altair/vegalite/__init__.py", line 2, in <module>
>     from .v5 import *
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/altair/vegalite/v5/__init__.py", line 2, in <module>
>     from altair.expr.core import datum
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/altair/expr/__init__.py", line 7, in <module>
>     from altair.expr.core import ConstExpression, FunctionExpression
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/altair/expr/core.py", line 6, in <module>
>     from altair.utils import SchemaBase
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/altair/utils/__init__.py", line 14, in <module>
>     from .plugin_registry import PluginRegistry
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/altair/utils/plugin_registry.py", line 13, in <module>
>     T = TypeVar("T")
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/typing_extensions.py", line 1418, in __new__
>     _set_default(typevar, default)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/typing_extensions.py", line 1375, in _set_default
>     type_param.__default__ = None
>     ^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: attribute '__default__' of 'typing.TypeVar' objects is not writable/

```

### What would you like to happen instead?

I would like altair to import successfully. I am not capable of understanding the issue or articulating it further, but I'm sure this would be very simple for the developers to understand. Pardon the lack of information.

### Which version of Altair are you using?

5.4.1

**Comment by benjamin5988** [comment]
downgrading to 5.3.0 made the issue go away

**Comment by dangotbanned** [comment]
> Hi [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/100963760?s=64&amp;v=4">@benjamin5988](https://github.com/benjamin5988), what version of Python are you using? There is known incompatibility with Python 3.13. We'll be doing an altair 5.5.0 release that will support Python 3.13 soon.

@jonmmease I linked this one in a bit of a rush [yesterday](https://github.com/vega/altair/issues/3692#event-15402413089) after noticing `3.13` in the error output:

> ```Traceback (most recent call last):
>   File "/home/bketter/csteis_working/11012024_NA2SO40pt1_FESO40pt001_NpH4_no6/autoeis_runscript_11012024_NA2SO40pt1_FESO40pt001_NpH4_no6.py", line 7, in <module>
>     import autoeis as ae
>   File "/home/bketter/.conda/envs/csteis_4/lib/python3.13/site-packages/autoeis/__init__.py", line 6, in <module>
> ```                                            ^^^^^^^^^^

**Comment by dangotbanned** [comment]
Closing, following https://github.com/vega/altair/pull/3699


@benjamin5988 please update to https://github.com/vega/altair/releases/tag/v5.5.0

**Comment by dangotbanned** [comment]
Closing, following https://github.com/vega/altair/pull/3699


@benjamin5988 please update to https://github.com/vega/altair/releases/tag/v5.5.0
